name: Release and publish

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          npm i
          npm run release
          echo "::set-output name=file::$(ls *.vsix)"
          zip --junk-paths ikosak-sync-now_${{ steps.tag_name.outputs.current_version }}.zip *.vsix

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.changelog_reader.outputs.version }}
          name: Release ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./ikosak-sync-now_${{ steps.tag_name.outputs.current_version }}.zip
          asset_name: ikosak-sync-now_${{ steps.tag_name.outputs.current_version }}.zip
          asset_content_type: application/zip

  publish:
    name: Publish to marketplace
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out

      - name: Publish
        run: |
          npm install
          VSCE_TOKEN=${{ secrets.VSCE_TOKEN }} npm run publish